name: Detect Projects

outputs:
  project-dirs: ${{ steps.get-project-dirs.outputs.PROJECT_DIRS }}

runs:
  using: "composite"
  steps:
    - name: Get go.mod files
      id: get-mod-files
      run: |
        go_mod_files=$(find . -name go.mod)
        echo "MOD_FILES=$go_mod_files" >> $GITHUB_OUTPUT

    - name: Get project directories
      id: get-project-dirs
      run: |
        project_dirs=$(echo $MOD_FILES | xargs -n1 dirname | sort -u)
        echo "PROJECT_DIRS=$project_dirs" >> $GITHUB_OUTPUT
