name: CI

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory to run the CI in"
        required: true
        type: string

permissions:
  contents: read
  pull-requests: read
  checks: write

env:
  WORKING_DIRECTORY: ${{ inputs.working-directory }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: ${{ env.WORKING_DIRECTORY }}/go.mod

      - name: Go Vet
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: go vet ./...

      - name: Go Lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6
        with:
          version: latest
          working-directory: ${{ env.WORKING_DIRECTORY }}

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: ${{ env.WORKING_DIRECTORY }}/go.mod

      - name: Go Fmt
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: go fmt ./...

      - name: Check changed files
        run: |
          git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: ${{ env.WORKING_DIRECTORY }}/go.mod

      - name: Go Test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: go test -v ./...
