name: CI

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory to run the CI in"
        required: true

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    working-directory: ${{ github.event.inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: ./go.mod

      - name: Go Vet
        run: go vet ./...

      - name: Go Lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6
        with:
          version: latest

  format:
    runs-on: ubuntu-latest
    working-directory: ${{ github.event.inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: ./go.mod

      - name: Go Fmt
        run: go fmt ./...

      - name: Check changed files
        run: |
          git diff --exit-code

  test:
    runs-on: ubuntu-latest
    working-directory: ${{ github.event.inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: ./go.mod

      - name: Go Test
        run: go test -v ./...
