name: DevContainer

on:
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**/*
      - .tool-versions

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build DevContainer
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: false
          tags: ${{ github.repository }}:devcontainer
