name: DevContainer

on:
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**/*
      - .tool-versions

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: Build DevContainer
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: false
          tags: ${{ github.repository }}:devcontainer
