name: Lib DMARC CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      working-directory: ./lib/dmarc
