name: Lib DMARC CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_DIR: ./lib/dmarc

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      working-directory: ${{ env.PROJECT_DIR }}
