name: libs/common

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - libs/common/**
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    # uses: ./.github/workflows/_ci.yml
    # with:
    #   working-directory: ./libs/common
