name: libs/common

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - libs/common/**
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    # uses: ./.github/workflows/_ci.yml
    # with:
    #   working-directory: ./libs/common
